# Generated by Django 2.2.5 on 2019-09-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_approved', models.IntegerField(default=0)),
                ('cancel_request_date', models.DateTimeField()),
                ('cancel_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField()),
                ('synonms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(default='2019-08-31 18:23:22.000000')),
                ('post_excerpt', models.TextField(default='Deliver as early as possible')),
                ('post_type', models.CharField(default='shop_order', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('stock_status', models.TextField()),
                ('total_sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_item_meta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_key', models.CharField(max_length=100)),
                ('meta_value', models.CharField(max_length=100)),
                ('order_item_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_meta_post_id', to='product.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_name', models.TextField()),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_post_id', to='product.Post')),
            ],
        ),
    ]
