# Generated by Django 2.2.5 on 2019-09-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_nicename', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_registered', models.DateTimeField()),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
    ]
