# Generated by Django 2.2.5 on 2019-09-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190908_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
