# Generated by Django 2.2.5 on 2019-10-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190908_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
