# Generated by Django 2.2.5 on 2019-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petpal_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
