# Generated by Django 2.2.5 on 2019-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20191005_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpal_user',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
